# docker-compose.yml

version: '3.8'

services:
  server:
    image: "rumppel/diploma-project_server:latest"
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    ports:
      - "8080:3001"
    env_file:
      - server/.env
    networks:
      - my_bridge_network
  
  client:
    image: "rumppel/diploma-project_client:latest"
    ports:
      - "80:5173"
    env_file:
      - client/.env
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge
