# docker-compose.yml

version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_TOKEN=${MONGODB_TOKEN}
      - SESSION_SECRET=${SESSION_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - MONGODB_TOKEN=${MONGODB_TOKEN}
      - SESSION_SECRET=${SESSION_SECRET}
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
