# docker-compose.yml

version: '3.8'

services:
  server:
    image: "rumppel/diploma-project_server:latest"
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - server/.env
  
  client:
    image: "rumppel/diploma-project_client:latest"
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile
    ports:
      - "82:82"
    env_file:
      - client/.env
