# docker-compose.yml

version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
