# docker-compose.yml

version: '3.8'

services:
  server:
    image: "diploma-project_server:latest"
    ports:
      - "3001:3001"
  
  client:
    image: "diploma-project_client:latest"
    ports:
      - "81:81"
