# docker-compose.yml

version: '3.8'

services:
  server:
    image: "diploma-project_server:latest"
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  
  client:
    image: "diploma-project_client:latest"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
