name: Deploy diploma-project to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        docker-compose -f docker-compose.yml build
        docker tag diploma-project_server:latest ${{ secrets.DOCKER_USERNAME }}/diploma-project_server:latest
        docker tag diploma-project_client:latest ${{ secrets.DOCKER_USERNAME }}/diploma-project_client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/diploma-project_server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/diploma-project_client:latest

    - name: Deploy to EC2
      run: |
        # Записуємо вміст SSH ключа у файл
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
        
        scp -o StrictHostKeyChecking=no -i ec2_key.pem docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/docker-compose.yml
        
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          
          echo "MONGODB_TOKEN=${{ secrets.MONGODB_TOKEN }}" > diploma-project/server/.env
          echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" >> diploma-project/server/.env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > diploma-project/server/.env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> diploma-project/server/.env
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" > diploma-project/server/.env
          echo "S3_REGION=${{ secrets.S3_REGION }}" >> diploma-project/server/.env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" > diploma-project/server/.env
          echo "VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}" >> diploma-project/client/.env
          ls -la
          cat diploma-project/client/.env
          cd diploma-project
          docker-compose down
          docker-compose pull
          docker-compose up -d
        EOF
        
        # Видаляємо файл з SSH ключем
        rm ec2_key.pem
