name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # або ваша основна гілка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/client:latest ./client
        docker build -t ${{ secrets.DOCKER_USERNAME }}/server:latest ./server
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tg-bot:latest ./tg-bot
        docker push ${{ secrets.DOCKER_USERNAME }}/client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tg-bot:latest

    - name: Create .env file in client
      run: |
        mkdir -p client
        echo "VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}" >> client/.env

    - name: Create .env file in server
      run: |
        mkdir -p server
        echo "MONGODB_TOKEN=${{ secrets.MONGODB_TOKEN }}" >> server/.env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> server/.env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> server/.env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> server/.env
        echo "S3_REGION=${{ secrets.S3_REGION }}" >> server/.env
        echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> server/.env

    - name: Create .env file in tg-bot
      run: |
        mkdir -p tg-bot
        echo "MONGODB_TOKEN=${{ secrets.MONGODB_TOKEN }}" >> tg-bot/.env
        echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" >> tg-bot/.env

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Creating .env file"
          echo MONGODB_TOKEN=${{ secrets.MONGODB_TOKEN }} >> .env
          echo SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env
          echo TG_TOKEN=${{ secrets.TG_TOKEN }} >> .env
          docker pull ${{ secrets.DOCKER_USERNAME }}/client:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/server:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/tg-bot:latest
          cd diploma-project/
          docker-compose down
          docker-compose up -d
