name: Deploy diploma-project to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker images
      run: |
        # cd diploma-project
        docker-compose build
        docker tag diploma-project_server:latest ${{ secrets.DOCKER_USERNAME }}/diploma-project_server:latest
        docker tag diploma-project_client:latest ${{ secrets.DOCKER_USERNAME }}/diploma-project_client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/diploma-project_server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/diploma-project_client:latest

    - name: Deploy to EC2
      run: |
        # Записуємо вміст SSH ключа у файл
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
        
        # Підключаємося до EC2 та запускаємо Docker контейнер
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "MONGODB_TOKEN=${{ secrets.MONGODB_TOKEN }}" > .env
          echo "TG_TOKEN=${{ secrets.TG_TOKEN }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" > .env
          echo "S3_REGION=${{ secrets.S3_REGION }}" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" > .env
          echo "VITE_MAPBOX_TOKEN=${{ secrets.VITE_MAPBOX_TOKEN }}" >> .env
          ls -la
          cat .env
          docker pull ${{ secrets.DOCKER_USERNAME }}/diploma-project_server:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/diploma-project_client:latest
          docker stop diploma-project_server || true
          docker stop diploma-project_client || true
          docker rm diploma-project_server || true
          docker rm diploma-project_client || true
          docker-compose -f /path/to/your/docker-compose.yml up -d
        EOF
        
        # Видаляємо файл з SSH ключем
        rm ec2_key.pem
